###GET

GET http://localhost:3000/musics



###GET
GET http://localhost:3000/users


###POST
POST http://localhost:3000/register
Content-Type: application/json
{
    "name": "Eyosi",
    "email": "eyosicoc@gmail.com",
    "password": "21372442"
}